# Generated by Django 2.0.5 on 2019-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190509_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='from_mail',
            name='form_mail_add',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
