# Generated by Django 2.0.5 on 2019-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190510_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='from_mail',
            name='form_mail_add',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='to_mail',
            name='to_mail',
            field=models.CharField(max_length=30),
        ),
    ]
