# Generated by Django 2.0.5 on 2019-05-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20190511_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=10)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
