# Generated by Django 2.0.5 on 2019-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.GenericIPAddressField()),
                ('mem_total', models.CharField(max_length=20)),
                ('mem_free', models.CharField(max_length=20)),
                ('free_cpu_percent', models.CharField(max_length=20)),
                ('use_time', models.CharField(max_length=20)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
