# Generated by Django 2.0.5 on 2019-04-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='mem_total',
        ),
    ]
