# Generated by Django 2.0.5 on 2019-05-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_monitor_mem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='free_cpu_percent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='mem_free',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
