# Generated by Django 2.0.5 on 2019-05-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20190514_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='min_1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='min_15',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='min_5',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
