# Generated by Django 2.0.5 on 2019-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('community', models.CharField(max_length=10)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
