# Generated by Django 2.0.5 on 2019-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmc_admin', '0002_host_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_info',
            name='total_memo',
            field=models.CharField(default=55, max_length=20),
            preserve_default=False,
        ),
    ]
