# Generated by Django 2.0.5 on 2019-05-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmc_admin', '0003_host_info_total_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='host_name',
            field=models.CharField(max_length=30),
        ),
    ]
