# Generated by Django 2.0.5 on 2019-05-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmc_admin', '0006_auto_20190513_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='total_memo',
            field=models.CharField(max_length=50),
        ),
    ]
