# Generated by Django 2.0.5 on 2019-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmc_admin', '0008_auto_20190514_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='int_info',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='host_info',
            name='total_memo',
            field=models.CharField(max_length=20),
        ),
    ]
